### PR TITLE
Release v1.2.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
https://github.com/mattermost/mattermost-plugin-apps/pull/380 is the past PR to go into the release before QA starts testing.

#### Ticket Link
Part of https://github.com/mattermost/mattermost-plugin-apps/issues/378

### CODE REVIEW

**Comment by hanzei** [comment]
Note to self: include changes from https://github.com/mattermost/mattermost-plugin-apps/commit/0856d8f8eac70040d6715f7c3733a3d3ca288ddc

**Comment by levb** [comment]
Talked with @catalintomai, let's include servicenow (deprecated) as the "dummy" app to deploy the release with.

**Review by levb — CHANGES_REQUESTED** [review]
Add `servicenow` (current version, that says deprecated) to the apps list?

**Comment by hanzei** [comment]
@levb https://github.com/mattermost/mattermost-plugin-apps/blob/5627d32fb56c432822ed8fcab5217b0d117eef3b/assets/manifests.json#L2?

**Comment by hanzei** [comment]
@DHaussermann The release is ready for your final review

**Review by DHaussermann — APPROVED** [review]
Tested and passed

Release testing summary posted here https://github.com/mattermost/mattermost-plugin-apps/issues/378#issuecomment-1362200190

- I have done a quick sanity check for a couple new commits.
- Ensured new AWS bundle validate in `appctl` works
- Ensured Zendesk `0.3.0` is in the manifest now.

LGTM!

**Pull request merged**
