### PR TITLE
Fixed MM-36358, bad merge resulting in crash

### PR DESCRIPTION
**Pull request by levb**
fixed the crash resulting from a bad merge.

PS, not sure how the e2e test passed before, did it?

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by catalintomai — APPROVED** [review]

**Review by hanzei — APPROVED** [review]
Good catch :+1:

**Comment by hanzei** [comment]
The 2E2 tests only test an HTTP app, not an AWS one which this PR fixes.

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
- Plugin crash resolved 
- Plugin is running normally and if functional
LGTM!

**Comment by DHaussermann** [comment]
Thanks @levb for resolving this. Please merge.

**Pull request merged**
