### PR TITLE
Release v1.1.1

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

- https://github.com/mattermost/mattermost-plugin-apps/pull/368

#### Ticket Link

https://github.com/mattermost/mattermost-plugin-apps/issues/385

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM

There are some places in the code base where the version number of the plugin matches a version used there. Should these also get an update?

**Review by levb — APPROVED** [review]

**Comment by mickmister** [comment]
> There are some places in the code base where the version number of the plugin matches a version used there. Should these also get an update?

@hanzei Thanks for pointing this out. I now updated the version in the docker compose file.

There are 10+ other places where this version number is referenced, and all seem benign for the purpose of this release. I'm thinking we should only update those references when there is a significant aspect that changes in that context.

**Comment by mickmister** [comment]
@levb Any idea why CI is failing at `TestSingleServer/OAuth2User_and_bot_calls_can_expand_OAuth2App`? https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-apps/3007/workflows/426f1266-bea9-43e8-9697-f304511c1fe2/jobs/17221

**Comment by levb** [comment]
@mickmister no clue, @hanzei filed the tickets, there is at least 1 other test flaking for unknown reason. I am investigating. Meanwhile, I triggered a re-run, let's see if it succeeds.

**Comment by levb** [comment]
@mickmister is this PR still needed?

**Pull request closed without merging**
