### PR TITLE
Enable OAuth and Bot accounts for E2E tests

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
OAuth Service Provider and Bot Account creation need to be enabled for the E2E tests.

#### Ticket Link
Related to https://github.com/mattermost/mattermost-plugin-apps/pull/157

Also fixes https://mattermost.atlassian.net/browse/MM-35099

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Comment by mickmister** [comment]
I enabled the oauth provider but not bot accounts in the e2e test. Was that the issue?

https://github.com/mattermost/mattermost-plugin-apps/blob/a8104b42a602d035636746f1f35aead4fa43fe5c/e2e/cypress/integration/bindings/channel_header_spec.ts#L29

**Review by mickmister — APPROVED** [review]

**Comment by hanzei** [comment]
@mickmister I missed that the config values also get set in the test itself. Do you have a strong opinion on where the default config set (i.e. plugins, bot, oauth enabled) should be set? In CI or in the cypress files?

**Comment by mickmister** [comment]
@hanzei 1/5 Let's have the "configurable" settings in the cypress test, i.e. oauth2 and bot account settings. This would allow us to test code paths where these values are not set.

**Comment by hanzei** [comment]
While investigating why the e2e fails I found out that the Apps plugin doesn't reload the MM config when it changes (https://mattermost.atlassian.net/browse/MM-35099). 247f7f0417be285421b5e065032d081d33d92322 does it that.

@levb @mickmister PTAL

**Review by iomodo — APPROVED** [review]

**Review by mickmister — APPROVED** [review]
LGTM :+1:  Thanks @hanzei

**Pull request merged**
