### PR TITLE
Include JWT secret in test app startup message

### LINKED ISSUE #392: Installing the test app fails searching the bindings
I'm trying to get the test app up and running, but for some reason gives signature error in the `/app/v1/bindings` call.

Screenshot 2022-11-18 at 13 10 11

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
That should make it easier for people to find the secret and serves as a reminder to set it.

#### Ticket Link
Fixes #392

### CODE REVIEW

**Review by javaguirre — APPROVED** [review]
I don't if it's in the docs, but that also would help big time. 💯 

Thank you @hanzei !

**Comment by hanzei** [comment]
@javaguirre which docs are you refering to?

**Comment by javaguirre** [comment]
https://developers.mattermost.com/integrate/apps/

**Comment by javaguirre** [comment]
@hanzei I see it's ACTUALLY in the docs, I don't know why I didn't get there 🤦 

https://developers.mattermost.com/integrate/apps/quickstart/quick-start-jwt/#download-and-start-the-app

**Pull request merged**
