### PR TITLE
[MM-39951] Guard ensureBot with mutex

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Downstream changes from https://github.com/mattermost/mattermost-plugin-api/pull/107 to fix https://mattermost.atlassian.net/browse/MM-39951

The PR targets https://github.com/mattermost/mattermost-plugin-apps/pull/291 to minimize the diff. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39951

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann Is there anything you need from my side to test this PR?

**Comment by hanzei** [comment]
@DHaussermann Gentle bump on the question above. Does it make sense to test the PR post merge?

**Comment by hanzei** [comment]
Sorry, had to force push to fix the history.

**Comment by hanzei** [comment]
Skipping QA testing as it's a simple change

**Pull request merged**
