### PR TITLE
Hard-removed Kubeless - crashed the tests in mysterious way

### PR DESCRIPTION
**Pull request by levb**
#### Summary
Hard-removed all Kubeless references: after upgrading to MacOS Monterey and go 1.17.4 I got a crash in `sync.Once` while running some of the tests. `git bisect` narrowed it down to the Kubeless PR (#222), removing Kubeless fixed the tests.

Since we already decided to remove/deprecate Kubeless support this seemed a no-brainer.

cc @hanzei who is out

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Review by hanzei — COMMENTED** [review]
@levb Do the added built flags in https://github.com/mattermost/mattermost-plugin-apps/pull/291 also resolve this issue?

**Comment by levb** [comment]
> @levb Do the added built flags in #291 also resolve this issue?

Yes, but `test-e2e` still crashed, 
image

**Comment by hanzei** [comment]
@levb Can you still reproduce this issue when running `make test-e2e`?

**Comment by levb** [comment]
@hanzei on `master` now - both `make test` and `make test-e2e` crash on my machine; removing Kubeless removes the test crashes.

This PR is already absorbed in https://github.com/mattermost/mattermost-plugin-apps/pull/296, so I am going to close it, but 2/5 we should remove Kubeless, as in #296.

**Pull request closed without merging**
