### PR TITLE
[MM-36227] Delete manifest when uninstalling an app

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
When an apps is uninstall, the manifest should also get removed from the store. Otherwise it just lies around forever as there is no install command to target it. All install commands in on-prem mode bring there own manifest anyway.

In cloud, we need to keep the manifest as the install commands only targets a listed manifest.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36227

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Review by levb — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann Can this be tested as part of https://github.com/mattermost/mattermost-plugin-apps/pull/191?

**Comment by DHaussermann** [comment]
@hanzei can you please pull master into this now that https://github.com/mattermost/mattermost-plugin-apps/pull/191 was merged?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Manifests are now removed from the store on uninstall for on-prem mode
- No changes for "listed" apps when running in Cloud mode

LGTM!

**Pull request merged**
