### PR TITLE
[MM-49164] Include apps that can be deployed as plugins but aren't in Marketplace response

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
E.g. the ServiceNow App _can_ be deployed as a plugin, but isn't in Cloud. `api/v1/marketplace?include_plugins=false` should return it.

This PR relaxes the checks around `includePluginApps` to only filter the apps out that are deployed as plugins or can only be deployed as plugins.

#### TODO
- [x] https://github.com/mattermost/mattermost-plugin-apps/blob/71155dd04c7fac09cf0e4ebb2c150a55cd45774d/server/httpin/admin.go#L158 should check for an match to `true`.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-49164

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Review by mickmister — APPROVED** [review]
Nice!

**Comment by hanzei** [comment]
@DHaussermann I would like to get this fix merged ASAP. Would you please take a look?

**Comment by DHaussermann** [comment]
@hanzei sorry I don't quite understand how I'd go about validating this change. 
So, right now we don't support apps that are deployed asa plugin at all and this changes fixes it?

Can you provide some guidance for testing this. And - if I'm understanding an app/repo that is currently affected.

**Comment by hanzei** [comment]
@DHaussermann I've updated the JIRA ticket for QA test steps. Please let me know if you need any additional guidance.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Followed steps as per Dev
- The Service  Now app does show in marketplace modal as expected 

LGTM!

Thanks @hanzei

**Pull request merged**
