### PR TITLE
OpenFaaS part 3: support multiple deployment types for Apps

### PR DESCRIPTION
**Pull request by levb**
NOTE: This PR replaces https://github.com/mattermost/mattermost-plugin-apps/pull/252, squashed the history and didn't want to force-push even though there were no comments yet.

./examples will be adjusted in an upcoming PR (part 4, OpenFaaS)

- Replaced `Manifest.AppType` with `App.DeploymentType` in `./apps/deploy*.go`.
- Added separate, optional deployment type-specific fields to `Manifest`: `HTTP`, `AWSLambda`, `Kubeless`, and `Plugin`.
- Changed the Install, uninstall, enable, disable REST APIs
- `appsctl aws|kubeless provision` now stores the listed manifest to Mattermost, optionally installs the App
- Backwards (0.7.0) compatibility

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by levb** [comment]
Documentation PR: https://github.com/mattermost/mattermost-developer-documentation/pull/939, cc @justinegeffen

**Review by catalintomai — APPROVED** [review]

**Review by DHaussermann — APPROVED** [review]
Testing deferred until after the post merge to be tested alongside other PRs.
removing labels.

**Comment by hanzei** [comment]
@levb Heads up that there are merge conflicts to resvole

**Comment by levb** [comment]
Docs are in https://github.com/mattermost/mattermost-developer-documentation/pull/939

**Pull request merged**
