### PR TITLE
[MM-31508] Rename URL to Path in Call

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Rename URL to Path in Apps Call

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31508

#### Related PRs
- https://github.com/mattermost/mattermost-webapp/pull/7566
- https://github.com/mattermost/mattermost-redux/pull/1370
- https://github.com/mattermost/mattermost-mobile/pull/5186
- https://github.com/mattermost/mattermost-app-zendesk/pull/29
- https://github.com/mattermost/mattermost-app-servicenow/pull/1

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM

**Review by levb — APPROVED** [review]
Do the user-agents (webapp, mobile) not depend on this field's name? If they do, do we have the corresponding PRs? And if they do not explicitly depend on the Call attributes - 👍 .

**Comment by hanzei** [comment]
@levb There are PRs for webapp and redux, but not for mobile.

**Comment by catalintomai** [comment]
> @levb There are PRs for webapp and redux, but not for mobile.

Would be useful to have all PR's related to this change (including the Zendesk/ServiceNow ones) referenced here to be reviewed in bulk.

**Comment by hanzei** [comment]
@catalintomai Good point, updated the description

**Pull request merged**
