### PR TITLE
Make getOAuth2User use interface{} and not map[string]interface{} to unmarshal the value

### PR DESCRIPTION
**Pull request by levb**

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
Any reason why the function accepts an interface to populate, rather than returning a concrete type?

**Comment by levb** [comment]
@mickmister it's a custom entity, can even be a string. See https://github.com/levb/mattermost-app-productboard/blob/master/connect.go#L42 as an example.

**Review by hanzei — APPROVED** [review]
:+1:

**Comment by hanzei** [comment]
@levb Should this PR be merged after `v0.5.0` is cut?

**Comment by levb** [comment]
@hanzei it shouldn't affect anyone, objects should still unmarshal as maps; but no rush.

**Pull request merged**
