### PR TITLE
Fix app install flow, more logging

### PR DESCRIPTION
**Pull request by levb**
#### Summary
- Improved ensureBot to avoid a username conflict with existing non-bot users by also trying a `username-app` suffix.
- Fixed the `mm.Bot.Get` to include deleted bot records; `mm.Bot.UpdateActive` executed just before appeared to take time to propagate. This fixes the install -> uninstall -> reinstall flow, likely https://mattermost.atlassian.net/browse/MM-48829?
- Added more logging to the app install flow.
- Added `linux-amd64` to the dev build to quicken uploads to cloud servers

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48829

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Review by javaguirre — APPROVED** [review]
👌

**Comment by DHaussermann** [comment]
@levb I saw some flakey behavior but maybe unrelated to these changes

Saving Zendesk config took 2 attempt and bindings delivery was a bit flakey at 1st

```
Jan 19 16:40:44.791 DEBUG (server/proxy/expand.go:197): failed to expand field acting_user

[11:40 AM](https://dkh-new-7-5.test.mattermost.cloud/eadsf/pl/j3wx1uft6pgafk36ezzeai9kar)
Jan 19 16:40:44.854 DEBUG (server/proxy/bindings.go:67): failed to fetch app bindings
```
Expanded logging and bot name functionality are both working as expected. If this PR does not affect bindings delivery I would merge. 

I can keep investigating on new server to see if a follow-up issue is needed.

**Comment by DHaussermann** [comment]
@lev I have now repeated Zendesk testing with this build on a new server. 
- Saving config to the store worked on the 1st attempt
- Bindings delivery has been accurate and consistent 
- The logging - set to DEBUG - showed nothing of concern.

I would be comfortable merging this. It seems unlikely the bahavior I saw early on with previous server was related to this specific PR

LGTM!

Unless if have further suggestions for functional testing, I'd say we can merge.

**Review by DHaussermann — APPROVED** [review]
Tested and passed as per comment above

**Pull request merged**
