### PR TITLE
[MM-58505] Fix group channel expand

### PR DESCRIPTION
**Pull request by sblaisot**
#### Summary

Having `channel: summary` in the expand section of an app (using app framework) make it unusable in the context of a group channel with the error message

```
failed to expand context: failed post-expand consistency check: expanded channel's team ID  is different from user agent context 1ntjrqrqdjy8mffhoc44g1e9zr
```

This is because, like Direct channels, the Group channel type has no TeamID so the consistency check fail and the expand fail, preventing from firing the application call.

This pull request fixes that behavior by ignoring Group Channels on the TeamID consistency check

#### Ticket Link

Fixes mattermost/mattermost#27271 and JIRA [MM-58505](https://mattermost.atlassian.net/browse/MM-58505)

### CODE REVIEW

**Review by hanzei — COMMENTED** [review]
Makes sense :+1: 

Can this change be covered by a test?

**Comment by sblaisot** [comment]
This can probably be tested. Unfortunately I don't have the required golang skills to add the test myself and I have seen no test on directChannel either so I have no example.

**Review by hanzei — APPROVED** [review]
Fair, let's get the fix merged

**Review by mickmister — APPROVED** [review]

**Comment by hanzei** [comment]
Thanks @sblaisot :+1:

**Pull request merged**
