### PR TITLE
Isolate client dependencies in upstream

### PR DESCRIPTION
**Pull request by levb**
Working on Kubeless integration, I ran into dependency conflicts. One way out I found was to isolate each upstream with dependencies into its own go module, and manage the dependencies there.

This PR accomplishes that for the existing code base.

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
LGTM :+1:

**Review by catalintomai — APPROVED** [review]

**Comment by levb** [comment]
@DHaussermann this is now merged with `master` and ready to be tested. I still need to change the `autolink` example to return `PluginID` in its Manifest (now a requirement), but the rest (HTTP, AWS) is testable.

@hanzei @catalintomai @mickmister - somewhat of a straight merge, but for plugin Apps I moved `PluginID` into the `Manifest` and the plugin is required to set it in its manifest.json; 3/5 it's cleaner this way.

**Comment by mickmister** [comment]
@levb When trying to update the apps plugin dependency in the autolink plugin (to use the new `Manifest` struct) I get this error:

```sh
> go get github.com/mattermost/mattermost-plugin-apps@f21ce39b77678d71f912e966c9fb103a46e53bcd

go get: github.com/mattermost/mattermost-plugin-apps@v0.6.1-0.20210625121129-b9aafaacbf9b updating to
        github.com/mattermost/mattermost-plugin-apps@v0.7.1-0.20210722151317-f21ce39b7767 requires
        github.com/mattermost/mattermost-plugin-apps/upstream/upaws@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

You can try it out using the autolink PR https://github.com/mattermost/mattermost-plugin-autolink/pull/164

**Comment by levb** [comment]
Going to close this PR in favor of https://github.com/mattermost/mattermost-plugin-apps/pull/222

**Pull request closed without merging**
