### PR TITLE
[MM-48223] Improve styling of /apps list

### PR DESCRIPTION
**Pull request by hanzei**
##### Before
Screenshot from 2023-01-30 17-11-26
##### After
Screenshot from 2023-01-30 17-10-34

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-48223

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Review by mickmister — COMMENTED** [review]
Can we use bulletted lists when we are listing something here? I don't think we need to worry about vertical real estate in this case

**Comment by levb** [comment]
@mickmister no lists in tables, AFAIK :(

**Comment by hanzei** [comment]
@mickmister I could not get md lists working in tables.

**Review by javaguirre — APPROVED** [review]
LGTM

**Pull request merged**
