### PR TITLE
Release v0.4.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Ticket Link
Part of https://github.com/mattermost/mattermost-plugin-apps/issues/153

### CODE REVIEW

**Review by catalintomai — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Comment by hanzei** [comment]
Awaiting https://github.com/mattermost/mattermost-plugin-apps/pull/157 and https://github.com/mattermost/mattermost-plugin-apps/pull/159

**Comment by hanzei** [comment]
@DHaussermann Ready for review

**Review by DHaussermann — APPROVED** [review]
Thanks Ben. Tested and passed the plugin. 
- Tested with production marketplace for happy path install
- Tested with some functional enhancements including reading from the config to see if bots is disabled
-  Regression tested correct behavior in off state
- Sanity checked respect for feature flag yet again :)

@hanzei 1 really quick point: the stock config point to no existing Lambdas and so nothing can be installed. This is pefect for the 1st marketplace test :). But it means we need a follow-up build for hackfest.

**Comment by DHaussermann** [comment]
@hanzei  One more thought. Scratch my last comment above. If we use this release for the hackfest - we have the option to deploy and Lambda in AWS that matches this config.

**Pull request merged**
