### PR TITLE
[MM-38123] Add AppField field which allows hiding the required star

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR adds a new field to the Field struct.  This field will allow users to hide the required star on a required field.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-38123

#### Related PR 
https://github.com/mattermost/mattermost-webapp/pull/8704

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by jfrerich** [comment]
Thanks, @mickmister :) If you feel like doing more reviews, feel free to checkout this related PR. https://github.com/mattermost/mattermost-webapp/pull/8704

**Review by catalintomai — APPROVED** [review]

**Review by larkox — APPROVED** [review]
LGTM, but I worry it may become a UX chaos if used wrong. I wonder if we should go more in the direction of a "required block" instead of individuals "hide required star". Not sure if the UX team has any opinion about that.

**Comment by hanzei** [comment]
I like the suggestion of @larkox of including the UX into this discussion.

**Comment by jfrerich** [comment]
All, after a meeting with Matt, Marina, Daniel, Michael, and myself, we concluded that we will be removing the required star from required fields. When viewing an app field, the required field will not have any unique identifiers (the *). Fields that are optional will have `(optional)` prepended to the label.

For further discussion see https://github.com/mattermost/mattermost-webapp/pull/8704

I'm closing this PR.

**Pull request closed without merging**
